Always Be Closing
=================
Peter Cummuskey <peterc@aetheric.co.nz>

A nodejs console project for managing tasks.

I named the task management methodology after watching a famous scene from the
movie Glengarry Glen Ross. The transcript follows below:

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

_In this scene, Blake (Alec Baldwin) is confronting the employees of a tough
Chicago real-estate office, Shelley Levene (Jack Lemmon), Ed Moss (Ed
Harris) and George Aaronow (Alan Arkin) while their unsympathetic supervisor
John Williamson (Kevin Spacey) looks on._

*Blake:* Let me have your attention for a moment! So you're talking about
what? You're talking about..._(puts out his cigarette)_...bitching about that
sale you shot, some son of a bitch that doesn't want to buy, somebody that
doesn't want what you're selling, some broad you're trying to screw and so
forth. Let's talk about something important. Are they all here?

*Williamson:* All but one.

*Blake:* Well, I'm going anyway. Let's talk about something important!
_(to Levene)_ Put that coffee down!! Coffee's for closers only. _(Levene
scoffs)_ Do you think I'm fucking with you? I am not fucking with you. I'm
here from downtown. I'm here from Mitch and Murray. And I'm here on a mission
of mercy. Your name's Levene?

*Levene:* Yeah.

*Blake:* You call yourself a salesman, you son of a bitch?

*Moss:* I don't have to listen to this shit.

*Blake:* You certainly don't pal. 'Cause the good news is -- you're fired. The
bad news is you've got, all you got, just one week to regain your jobs,
starting tonight. Starting with tonights sit. Oh, have I got your attention
now? Good. 'Cause we're adding a little something to this months sales
contest. As you all know, first prize is a Cadillac Eldorado. Anyone want to
see second prize? Second prize's a set of steak knives. Third prize is you're
fired. You get the picture? You're laughing now? You got leads. Mitch and
Murray paid good money. Get their names to sell them! You can't close the
leads you're given, you can't close shit, you ARE shit, hit the bricks pal and
beat it 'cause you are going out!!!

*Levene:* The leads are weak.

*Blake:* 'The leads are weak.' Fucking leads are weak? You're weak. I've been
in this business fifteen years.

*Moss:* What's your name?

*Blake:* FUCK YOU, that's my name!! You know why, Mister? 'Cause you drove a
Hyundai to get here tonight, I drove a eighty thousand dollar BMW. That's my
name!! _(to Levene)_ And your name is "you're wanting." And you can't play in
a man's game. You can't close them. _(at a near whisper)_ And you go home and
tell your wife your troubles. _(to everyone again)_ Because only one thing
counts in this life! Get them to sign on the line which is dotted! You hear
me, you fucking faggots?

_Blake flips over a blackboard which has two sets of letters on it: ABC, and
AIDA._

*Blake:* A-B-C. A-always, B-be, C-closing. Always be closing! Always be
closing!! A-I-D-A. Attention, interest, decision, action. Attention -- do I
have your attention? Interest -- are you interested? I know you are because
it's fuck or walk. You close or you hit the bricks! Decision -- have you made
your decision for Christ?!! And action. A-I-D-A; get out there!! You got the
prospects comin' in; you think they came in to get out of the rain? Guy
doesn't walk on the lot unless he wants to buy. Sitting out there waiting to
give you their money! Are you gonna take it? Are you man enough to take it?
_(to Moss)_ What's the problem pal? You. Moss.

*Moss:* You're such a hero, you're so rich. Why you coming down here and waste
your time on a bunch of bums?

_Blake sits and takes off his gold watch_

*Blake:* You see this watch? You see this watch?

*Moss:* Yeah.

*Blake:* That watch cost more than your car. I made $970,000 last year. How
much you make? You see, pal, that's who I am. And you're nothing. Nice guy? I
don't give a shit. Good father? Fuck you -- go home and play with your kids!!
_(to everyone)_ You wanna work here? Close!! _(to Aaronow)_ You think this is
abuse? You think this is abuse, you cocksucker? You can't take this -- how can
you take the abuse you get on a sit?! You don't like it -- leave. I can go out
there tonight with the materials you got, make myself fifteen thousand
dollars! Tonight! In two hours! Can you? Can you? Go and do likewise!
A-I-D-A!! Get mad! You sons of bitches! Get mad!! You know what it takes to
sell real estate?

_He pulls something out of his briefcase_

*Blake:* It takes brass balls to sell real estate.

_He's holding two brass balls on string, over the appropriate "area"--he puts
them away after a pause_

*Blake:* Go and do likewise, gents. The money's out there, you pick it up,
it's yours. You don't--I have no sympathy for you. You wanna go out on those
sits tonight and close, close, it's yours. If not you're going to be shining
my shoes. Bunch of losers sitting around in a bar. _(in a mocking weak voice)_
"Oh yeah, I used to be a salesman, it's a tough racket." _(he takes out large
stack of red index cards tied together with string from his briefcase)_ These
are the new leads. These are the Glengarry leads. And to you, they're gold.
And you don't get them. Why? Because to give them to you is just throwing them
away. _(he hands the stack to Williamson)_ They're for closers.
I'd wish you good luck but you wouldn't know what to do with it if you got it.
_(to Moss as he puts on his watch again)_ And to answer your question, pal:
why am I here? I came here because Mitch and Murray asked me to, they asked me
for a favor. I said, the real favor, follow my advice and fire your fucking
ass because a loser is a loser.

_He stares at Moss for a sec, and then picking up his briefcase, goes into
the inner office with Williamson_

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

